export const GET_COURSES_SUCCEEDED = 'GET_COURSES_SUCCEEDED';
export const GET_ASSIGNMENTS_REQUESTED = 'GET_ASSIGNMENTS_REQUESTED';
export const GET_ASSIGNMENTS_SUCCEEDED = 'GET_ASSIGNMENTS_SUCCEEDED';
export const GET_SUBMISSIONS_REQUESTED = 'GET_SUBMISSIONS_REQUESTED';
export const GET_SUBMISSIONS_SUCCEEDED = 'GET_SUBMISSIONS_SUCCEEDED';
