export const MOVE_CARD = 'MOVE_CARD';
export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_REQUESTED = 'CREATE_CARD_REQUESTED';
export const UPDATE_CARD_REQUESTED = 'UPDATE_CARD_REQUESTED';

export const FETCH_CARDS = 'FETCH_CARDS';

export const GET_DATABASE_CARDS_REQUESTED = 'GET_DATABASE_CARDS_REQUESTED';
export const GET_DATABASE_CARDS_SUCCEEDED = 'GET_DATABASE_CARDS_SUCCEEDED';